language: python
python: 3.4
script: python3 -m unittest discover tests/ "test_*"

deploy:
  provider: pypi
  user: adamkewley
  password:
    secure: KNNqkkyYIkuiEcjl3e+bGiRnOwO6u7lLOnhRXJ3RWB6dsNUXiGlnaHkj2hYF6P9HrxXij/8k8yvd6fvtIs8+desxbqv94LfFgsiHIsfWaBw9ZKf1YcBp4edsNBatzLunXK+H9vmQngqbZ6LbXA4MzQj5GGGrtdelQk954makYDQILqxc2O/sluB+KScL6JxohQqt3ml4OYfI5Io5DpVuY+Ow+WubSPr9+sSEUIn9WAZGXDYb1inA6c+NccgbeR/hpG96Hi7ZAx5k7oNZ+x4pGxd4O/wN+BgMEf/Q31FU/wX6nL1d3POGCbSGe1sj9X1YxzSro1NIkhvhdArTywPkcYysyAIgGlxT7ek1NDLgDz4dCpCTQVcCqPOL90lUYJIu8ppV/Us7SP5iZxh3Pt7QTYePo/Cf85obuAYh/RULDlgR4dv6BiTGOhpQGvN+ZlG7KajcvwRdMW97oJRp+WWXFhZzkM7ch2PWjP+QlrmGCImhOMnR5B9q9uNisl9+NL9jmMv1A/YPJ8+dnChxjgL3hitBKSU1I2Q1QfqwBjsGED4V2cmOO6NWQjVGjIM4SDntycBfRak0FiOXbEi4J6ozTr+CJI98UeTdIoHYrXyeRlAQd9Zwvy+jzFAMymM5Ek5ToQsoUV4FRAqI5hz63ld+cpdlj6VOxOBEIrd4gSFC+7U=

  distributions: sdist

  on:
    tags: true
